name: Setup Node

description: Setup Node & Install Dependencies

runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@v6
      with:
        node-version-file: .nvmrc
        package-manager-cache: false

    - name: Extract and install npm version from package.json
      id: get-npm-version
      run: |
        NPM_SPEC=$(jq -r '.devEngines.packageManager | "\(.name)@\(.version)"' package.json)
        TARBALL_PATH=$(corepack pack "$NPM_SPEC")
        npm install -g "$TARBALL_PATH"
      shell: bash

    - name: Install dependencies
      run: npm ci
      shell: bash
